### ISSUE TITLE
Integration Error - Failed to Setup

### ISSUE THREAD

**Issue by justinsanker** [Crewski/Pumpspy-HA#11]
I've had this working for over a month but for the past week of so the integration hasn't been able to connect to the cloud account.  Is there a way to log out and log back in?  I've had to do that on the phone app and it fixes it.  I've hit "reload integration" but that doesn't fix it.  Here's the error from the logs:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/pumpspy_ha/__init__.py:57
Integration: Pumpspy (documentation, issues)
First occurred: May 4, 2023 at 10:09:30 PM (5 occurrences)
Last logged: 9:59:43 AM

Error setting up entry Pumpspy (JS PumpSpy BBS) for pumpspy_ha
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/pumpspy_ha/__init__.py", line 57, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
![image](https://user-images.githubusercontent.com/20491444/236479915-be432126-40d0-4ba1-9311-fbcc2cdab80e.png)

**Comment by Crewski** [comment]
Hey @justinsanker , it's possible you just need to delete and re-setup the integration.  Unfortunately Pumpspy doesn't utilize a refresh token, which is why once a month you have to re-login to the app.  I made a change to save the password and re-login automatically.  I also made changes for people that don't have a battery backup system as the api endpoint is different.  So delete the integration, make sure its updated through HACS, and re-install it.  Hopefully that'll fix it.

**Comment by justinsanker** [comment]
That worked thanks @Crewski! I'm running v0.1.4.2 now.
